# Generated by Django 3.0.3 on 2020-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_auto_20200202_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Голоса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Голоса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
