# Generated by Django 3.0.3 on 2020-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20200219_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(default=0, help_text='-1, 0, 1', verbose_name='Голос'),
        ),
    ]
