# Generated by Django 3.0.3 on 2020-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_auto_20200219_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=0, verbose_name='Правильный ответ'),
        ),
    ]
